#ifndef __ESFERA_H_INCLUDED_
#define __ESFERA_H_INCLUDED_

#define RAIO_TERRA 128
#define PERIODO_ROT_TERRA 48
#define PERIODO_TRANS_TERRA PERIODO_ROT_TERRA*365
#define INCLINACAO_TERRA 23.5/180.0*PI
#define GRAVIDADE_TERRA 0.001
#define DIST_TERRA_SOL 1496*RAIO_TERRA

#define RAIO_SOL 7*RAIO_TERRA
#define PERIODO_ROT_SOL PERIODO_ROT_TERRA*28

#define INCLINACAO_MARTE 25.33/180.0*PI
#define PERIODO_ROT_MARTE PERIODO_ROT_TERRA*1.0275
#define PERIODO_TRANS_MARTE PERIODO_TRANS_TERRA*1.88
#define GRAVIDADE_MARTE GRAVIDADE_TERRA*0.378
#define RAIO_MARTE RAIO_TERRA/2
#define DIST_MARTE_SOL DIST_TERRA_SOL*1.52

#define INCLINACAO_VENUS 177/180*PI
#define PERIODO_ROT_VENUS PERIODO_ROT_TERRA*243
#define PERIODO_TRANS_VENUS PERIODO_TRANS_TERRA*.61
#define GRAVIDADE_VENUS GRAVIDADE_TERRA*.88
#define RAIO_VENUS RAIO_TERRA*.94873
#define DIST_VENUS_SOL DIST_TERRA_SOL*.72

#define INCLINACAO_MERCURIO .1/180.0*PI
#define PERIODO_ROT_MERCURIO PERIODO_ROT_TERRA*58
#define PERIODO_TRANS_MERCURIO PERIODO_TRANS_TERRA*.23
#define GRAVIDADE_MERCURIO GRAVIDADE_TERRA*.37
#define RAIO_MERCURIO RAIO_TERRA*.3824
#define DIST_MERCURIO_SOL DIST_TERRA_SOL*.387

#define INCLINACAO_JUPITER 3/180.0*PI
#define PERIODO_ROT_JUPITER PERIODO_ROT_TERRA*2.66
#define PERIODO_TRANS_JUPITER PERIODO_TRANS_TERRA*11
#define GRAVIDADE_JUPITER GRAVIDADE_TERRA*2.64
#define RAIO_JUPITER RAIO_TERRA*11
#define DIST_JUPITER_SOL DIST_TERRA_SOL*3

#define LATITUDES 15
#define LONGITUDES 15

#define PI 3.14159265358979

#define N_PLANETAS 6

#endif
